services:
  composer:
    image: composer:latest
    working_dir: /app
    volumes:
      - .:/app
    command: ["composer", "update"]

  #  postgres:
  #    image: postgres:latest
  #    container_name: postgres
  #    restart: always
  #    environment:
  #      POSTGRES_USER: postgres
  #      POSTGRES_PASSWORD: postgres
  #    volumes:
  #      - ./postgres:/var/lib/postgresql/data

  #  mysql:
  #    image: mysql:latest
  #    container_name: mysql
  #    restart: always
  #    environment:
  #      MYSQL_ROOT_PASSWORD=password
  #    volumes:
  #      - ./mysql:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - ./redis:/data
    command: redis-server --save 60 1 --loglevel warning


  php-fpm:
    image: hub.madelineproto.xyz/danog/madelineproto
    container_name: php-fpm
    restart: always
    volumes:
      - ./:/app
    command: ["php-fpm"]

  web_server:
    image: nginx:latest
    container_name: web_server
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./web.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php-fpm:
        condition: service_started
    ports:
      - 8000:80

  bot:
    image: hub.madelineproto.xyz/danog/madelineproto
    container_name: bot
    depends_on:
      composer:
        condition: service_completed_successfully
      #       postgres:
      #         condition: service_started
      redis:
        condition: service_started
    restart: on-failure:3
    working_dir: /app
    tty: true
    volumes:
      - .:/app
    command: ["php", "run.php"]
